# Generated by Django 5.2 on 2025-04-16 02:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('is_government', models.BooleanField(blank=True, null=True)),
                ('is_scolarshpis', models.BooleanField(blank=True, null=True)),
                ('bio', models.TextField(max_length=100)),
                ('number', models.IntegerField()),
                ('grade', models.CharField(choices=[('A++', '1'), ('B++', '2'), ('C++', '3')], max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('is_open', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
