# Generated by Django 5.2 on 2025-04-15 17:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=20)),
                ('catagory', models.CharField(choices=[('A-Class', 'AC'), ('B-Class', 'BC'), ('C-Class', 'CC'), ('D-Class', 'DC')], max_length=20)),
                ('bio', models.TextField(max_length=100)),
                ('number', models.IntegerField()),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('is_open', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
